name: Update Search Index and Deploy

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate search index
        uses: some-search-index-generator-action@v1
        with:
          input-dir: ./content
          output-file: ./static/search.json

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          if ! git diff-index --quiet HEAD --; then
            git commit -m "Auto-update search index [skip ci]"
            git pull origin main --rebase
            git push origin HEAD:main
          else
            git clean -fd
            git reset --hard HEAD
            echo "::notice:: No changes in search.json, skipping commit"
          fi